spring.application.name=careerwise

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/careerwise
spring.datasource.username=root
spring.datasource.password=Admin4526

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=*

# Server
server.port=8082

# Gemini API
gemini.api.key=${GEMINI_API_KEY}