spring.application.name=careerwise

# MySQL Database
spring.datasource.url=mysql://root:KgjNVUTqVGNxJsoEKJqwJZLfgHkMsDnR@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=KgjNVUTqVGNxJsoEKJqwJZLfgHkMsDnR

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=*

# Server
server.port=8082

# Gemini API
gemini.api.key=${GEMINI_API_KEY}